app/models.py
from .import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    __tablename__='users'
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(255))
    email =db.Column(db.String(255),unique=True,index=True)
    role_id=db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch=db.relationship('Pitch',backref='col',lazy='dynamic')
    pass_secure = db.Column(db.String(255))
    comments=db.relationship('Comment',backref='user',lazy='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
       return check_password_hash(self.pass_secure,password)

    @classmethod
    def get_user(cls,id):
        user= User.query.filter_by(id=id).first()
        return user

    def __repr__(self):
            return f'User {self.username}'

class Role(db.Model):
    __tablename__='roles'
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.String(255))
    users=db.relationship('User',backref='role',lazy='dynamic')

    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    __tablename__='pitch'

    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String)
    category=db.Column(db.String)
    description=db.Column(db.String)
    # time_posted=db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    comment=db.relationship('Comment',backref='comment',lazy='dynamic')
    
    
    def __repr__(self):
        return f'User {self.pitch}'

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_pitch(cls,id):
        pitch= Pitch.query.filter_by(user_id=id).all()
        return pitch
    @classmethod
    def get_pitch_id(cls,id):
        pitch= Pitch.query.filter_by(id=id).all()
        return pitch
# ******88RETURNS ALL PITCHES
    def get_all_pitch():
        pitch= Pitch.query.all()
        return pitch
    @classmethod
    def get_all_pitchs():
        pitch= Pitch.query.first()
        return pitch
    @classmethod
# Getting categories
    def get_pitch_category(cls,category):
        pitch= Pitch.query.filter_by(category=category).all()
        return pitch
class Comment(db.Model):
    __tablename__='comment'

    id=db.Column(db.Integer,primary_key=True)
    description=db.Column(db.String)
    upvote=db.Column(db.Integer)
    downvote=db.Column(db.Integer)
    time_posted=db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch_id=db.Column(db.Integer,db.ForeignKey("pitch.id"))
    # pitchcategory=db.relationship("Pitch",backref="category",lazy="dynamic")

   
    def save_new_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comment = Comment.query.filter_by(pitch_id=id).all()
        return reviews
    

    
   

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class AddPitch(FlaskForm):
    title=TextAreaField("Pitch Title",validators=[Required()])
    # category=TextAreaField("Category",validators=[Required()])
    category=RadioField("Category",choices=[("general","General"),("pickuplines","Pick Up Lines"),("interviewpitch","Interview Pitch"),("productpitch","Product Pitch"),("promotionpitch","Promotion")])
    description=TextAreaField("Description",validators=[Required()])
    submit=SubmitField('Submit')
class CommentInput(FlaskForm):
    description=TextAreaField("Comment:",validators=[Required()],)
    submit=SubmitField('Submit')

app/__init__.py
from werkzeug.utils import secure_filename
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

photos = UploadSet('photos',IMAGES)
mail=Mail()
# Initializing Flask Extensions
bootstrap=Bootstrap()
db=SQLAlchemy()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Pitch,Comment

from flask_login import login_required,current_user
from ..models import User
from  ..import db,photos
from .forms import UpdateProfile,AddPitch,CommentInput
from datetime import datetime


@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    message='Index Page'
    title = 'Home - Welcome to The Pitchpitches'
    # user=User.get_user(id)
    
    return render_template('index.html',title=title,message=message)


@main.route('/user/<uname>')
def profile(uname):
    

    user = User.query.filter_by(username = uname).first()
    user_id=user.id
    pitches=Pitch.get_pitch(user_id)
    
    
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user,pitches=pitches)



@main.route('/pitch/<category>')
def pitch(category):

    
   
    all_pitches=Pitch.query.filter_by(category=category).all()
    pitch=Pitch.query.filter_by(category=category).first()

    pitches=Pitch.get_pitch_category(category)
    form=CommentInput()
    
    if form.validate_on_submit():
        description=form.description.data
        
        new_comment=Comment(description=description,upvote=0,downvote=0,pitch_id=pitchess.id)
        # SAVE COMENT
        new_comment.save_new_comment()
        return redirect(url_for('.pitch',category=pitches.category))

        # return redirect(url_for('.movie',id = movie.id ))
    #
    pitches=Pitch.get_pitch_category(category)

    return render_template('categories.html',category = category,all_pitches=all_pitches,form=form)


@main.route('/user/pitch/<id>', methods = ['GET','POST'])
@login_required
def new_pitch(id):  
    pitch_form=AddPitch()
    user=User.get_user(id)
    if form.validate_on_submit():
        title=pitch_form.title.data
        category=pitch_form.category.data
        description=pitch_form.description.data
        new_pitch=Pitch(title=title,category=category,description=description,user_id=user.id)

        new_pitch.save_pitch()
        return redirect(url_for('.index',id=user.id))
    title='New Pitch'
    return render_template('pitches.html',title = title, pitch_form=pitch_form,user=user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block navbar%}
{%include 'navbar.html'%}
{%endblock%}

app/templates/categories.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
{% block content %}
<div class="container">
    <h2 style="text-align: center;">  {{ category.upper() }} </h2>
    <div class="row">
        <div class="col-md-4">
            <!-- <h3>{{ category.upper() }} Pitches</h3>     -->
            {{macro.displaycategory(pitches)}}
        </div>
        <div class="col-md-4">
            <P style="width: 30px;">{{wtf.quick_form(form)}}</P>
        </div>
    
    </div>
        <div class=""></div>  
</div>


{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
{% block content %}

<strong><h2>Welcome To PITCH4YOU!!</h2>
<p>In life, you only have 60 seconds to impress someone. 1 minute can make or break you. Want to make sure that you use your 1 minute to actually say something meaningful?</p>
<p>SIGN UP NOW AND START MAKING YOUR PITCHES!</p></strong>


{% endblock %}

app/templates/macros.html
{% macro displaypitches(pitch_list) %}

{% for pitch in pitch_list %}

<div class="col-md-4">
    <div class="card border-info mb-3" style="max-width: 18rem;">
        <div class="card-header">{{ pitch.title}}</div>
        <div class="card-body text-info">
    
            <p class="card-text">{{ pitch.description | truncate(30) }}</p>
        </div>
    </div>
</div>

{% endfor %}

{%endmacro%}

{% macro displaycategory(pitch_list) %}

{% for pitch in pitch_list %}


<div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header">{{ pitch.category.title()}}</div>
    <div class="card-body text-dark">

        <p class="card-text">{{ pitch.description | truncate(30) }}</p>
    </div>
</div>
{% endfor %}

{%endmacro%}

{% macro displayprofilepitch(pitch_list) %}

{% for pitch in pitch_list %}

<ul>
    <li>pitch.title</li>
</ul>
{% endfor %}
{%endmacro%}


{% macro displaycategories(pitchlist) %}

{% for pitch in pitchlist %}

<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
    <h2> {{ pitch.title}} </h2>
    <p> {{ pitch.description | truncate(30) }}</p>

</div>
{% endfor %}
{%endmacro%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> PITCH4YOU </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('main.pitch',category='general')}}">General</a></li>
                <li><a href="{{url_for('main.pitch',category='pickuplines')}}">Pickup Lines</a></li>
                <li><a href="{{url_for('main.pitch',category='productpitch')}}">Product Pitch</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li></li>
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
              </ul>
        </div>

    </div>
</div>

app/templates/pitches.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="">

            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}